//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.WebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name AppGetAllEmployeeDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppGetAllEmployeeData", ReplyAction="*")]
        CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse AppGetAllEmployeeData(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppGetAllEmployeeData", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse> AppGetAllEmployeeDataAsync(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppCreateNewEmployee", ReplyAction="*")]
        CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse AppCreateNewEmployee(CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppCreateNewEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse> AppCreateNewEmployeeAsync(CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppDeleteEmployee", ReplyAction="*")]
        CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse AppDeleteEmployee(CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppDeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse> AppDeleteEmployeeAsync(CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppGetAllEmployeeDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppGetAllEmployeeData", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequestBody Body;
        
        public AppGetAllEmployeeDataRequest() {
        }
        
        public AppGetAllEmployeeDataRequest(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AppGetAllEmployeeDataRequestBody {
        
        public AppGetAllEmployeeDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppGetAllEmployeeDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppGetAllEmployeeDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponseBody Body;
        
        public AppGetAllEmployeeDataResponse() {
        }
        
        public AppGetAllEmployeeDataResponse(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppGetAllEmployeeDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppGetAllEmployeeDataResult;
        
        public AppGetAllEmployeeDataResponseBody() {
        }
        
        public AppGetAllEmployeeDataResponseBody(string AppGetAllEmployeeDataResult) {
            this.AppGetAllEmployeeDataResult = AppGetAllEmployeeDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppCreateNewEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppCreateNewEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequestBody Body;
        
        public AppCreateNewEmployeeRequest() {
        }
        
        public AppCreateNewEmployeeRequest(CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppCreateNewEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public AppCreateNewEmployeeRequestBody() {
        }
        
        public AppCreateNewEmployeeRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppCreateNewEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppCreateNewEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponseBody Body;
        
        public AppCreateNewEmployeeResponse() {
        }
        
        public AppCreateNewEmployeeResponse(CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppCreateNewEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppCreateNewEmployeeResult;
        
        public AppCreateNewEmployeeResponseBody() {
        }
        
        public AppCreateNewEmployeeResponseBody(string AppCreateNewEmployeeResult) {
            this.AppCreateNewEmployeeResult = AppCreateNewEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppDeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppDeleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppDeleteEmployeeRequestBody Body;
        
        public AppDeleteEmployeeRequest() {
        }
        
        public AppDeleteEmployeeRequest(CRUDMVC.WebServiceReference.AppDeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppDeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public AppDeleteEmployeeRequestBody() {
        }
        
        public AppDeleteEmployeeRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AppDeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AppDeleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUDMVC.WebServiceReference.AppDeleteEmployeeResponseBody Body;
        
        public AppDeleteEmployeeResponse() {
        }
        
        public AppDeleteEmployeeResponse(CRUDMVC.WebServiceReference.AppDeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AppDeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppDeleteEmployeeResult;
        
        public AppDeleteEmployeeResponseBody() {
        }
        
        public AppDeleteEmployeeResponseBody(string AppDeleteEmployeeResult) {
            this.AppDeleteEmployeeResult = AppDeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CRUDMVC.WebServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CRUDMVC.WebServiceReference.WebService1Soap>, CRUDMVC.WebServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse CRUDMVC.WebServiceReference.WebService1Soap.AppGetAllEmployeeData(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest request) {
            return base.Channel.AppGetAllEmployeeData(request);
        }
        
        public string AppGetAllEmployeeData() {
            CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest inValue = new CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequestBody();
            CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse retVal = ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppGetAllEmployeeData(inValue);
            return retVal.Body.AppGetAllEmployeeDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse> CRUDMVC.WebServiceReference.WebService1Soap.AppGetAllEmployeeDataAsync(CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest request) {
            return base.Channel.AppGetAllEmployeeDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppGetAllEmployeeDataResponse> AppGetAllEmployeeDataAsync() {
            CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest inValue = new CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppGetAllEmployeeDataRequestBody();
            return ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppGetAllEmployeeDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse CRUDMVC.WebServiceReference.WebService1Soap.AppCreateNewEmployee(CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest request) {
            return base.Channel.AppCreateNewEmployee(request);
        }
        
        public string AppCreateNewEmployee(string data) {
            CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest inValue = new CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequestBody();
            inValue.Body.data = data;
            CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse retVal = ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppCreateNewEmployee(inValue);
            return retVal.Body.AppCreateNewEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse> CRUDMVC.WebServiceReference.WebService1Soap.AppCreateNewEmployeeAsync(CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest request) {
            return base.Channel.AppCreateNewEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppCreateNewEmployeeResponse> AppCreateNewEmployeeAsync(string data) {
            CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest inValue = new CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppCreateNewEmployeeRequestBody();
            inValue.Body.data = data;
            return ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppCreateNewEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse CRUDMVC.WebServiceReference.WebService1Soap.AppDeleteEmployee(CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest request) {
            return base.Channel.AppDeleteEmployee(request);
        }
        
        public string AppDeleteEmployee(string data) {
            CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest inValue = new CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppDeleteEmployeeRequestBody();
            inValue.Body.data = data;
            CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse retVal = ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppDeleteEmployee(inValue);
            return retVal.Body.AppDeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse> CRUDMVC.WebServiceReference.WebService1Soap.AppDeleteEmployeeAsync(CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest request) {
            return base.Channel.AppDeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUDMVC.WebServiceReference.AppDeleteEmployeeResponse> AppDeleteEmployeeAsync(string data) {
            CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest inValue = new CRUDMVC.WebServiceReference.AppDeleteEmployeeRequest();
            inValue.Body = new CRUDMVC.WebServiceReference.AppDeleteEmployeeRequestBody();
            inValue.Body.data = data;
            return ((CRUDMVC.WebServiceReference.WebService1Soap)(this)).AppDeleteEmployeeAsync(inValue);
        }
    }
}
